### ISSUE TITLE
Documentation should be more explicit

### ISSUE THREAD

**Issue by jonchan51** [AY1920S1-CS2103-T16-3/main#195]
- [x] #192 - Creation sessions are not saved
- [x] #183 - Filepaths
- [x] #179 - Need to load before importing (maybe explicitly say imported from import tab or something nicer)
- [x] #178 - Commands that do not require parameters should be explicitly mentioned to avoid this
- [x] #176 - Typo
- [x] #164 - Explain relative and absolute paths
