### ISSUE TITLE
Creation tab

### ISSUE THREAD

**Issue by jonchan51** [AY1920S1-CS2103-T16-3/main#196]
- [x] Sizing issues
  - [x] #174 ~Axis too small when image too small~ **rare use case; won't fix**
  - [x]  #189 cannot see axis when image too big **decreased image size**
- [x] Text would exceed image boundary **removed boundary check**
  - [x] #188 ~Wrong command entered but another exception given~ **not a bug; won't fix**
  - [x] #187 Example given in user guide would add text that exceeds image boundary **updated user guide**
  - [x] #170 Error is thrown even though text will clearly not exceed **updated user docs to make it clear that the x and y coordinates are for the centre of the text**
- [x] #169 
  - [x] Typo in error message **fixed**
  - [x] ~"Coordinates are valid but wrong error message (Error message should have said that there was no size argument provided)"~ **not a bug; won't fix**
