### ISSUE TITLE
Statistics Tab

### ISSUE THREAD

**Issue by jonchan51** [AY1920S1-CS2103-T16-3/main#197]
- [ ] #177 #173 Tag Usage UI (173 says it's after disliking a meme)
- [x] #172 Dislikes affecting likes
- [ ]  #171 Most Used Templates
- [x]  #163 Dislike implementation

**Comment by moziliar** [comment]
Most used templates will be pushed to v2.0
