### ISSUE TITLE
Templates

### ISSUE THREAD

**Issue by gary-lgy** [AY1920S1-CS2103-T16-3/main#52]
- [x] Add infra #69 
- [x] Create/Delete templates #94 
- [x] Generate memes using templates (by adding text to the template) #116 #134 
- [x]  Enhancements
  - [x] Rules as visual aid #132 
  - [x] Allow specifying font size and color #135 
  - [x] Display list of text added #142 
  - [x] Support edit/delete text #142 
  - [x] Move text with arrow keys #228
  - [x] List and find commands #222 
  - [x] Scale font size according to image size #226

**Comment by gary-lgy** [comment]
Feature is complete.
